language: python
python:
  - 3.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-scipy
  - sudo apt-get install -qq python3-nose
  - sudo apt-get install -qq python3-mock
install:
  - pip install pandas
  - pip install patsy
  - pip install msgpack-python
  - pip install redis
  - pip install flask
  - pip install simplejson
  - pip install pep8
  - pip install -r requirements.txt
  - cp src/settings.py.example src/settings.py
script:
  - nosetests -v --nocapture
  - pep8 --exclude=migrations --ignore=E501,E251,E265 ./
notifications:
  email: false
